# Generated by Django 6.0 on 2025-12-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imap_host', models.CharField(max_length=200)),
                ('imap_port', models.IntegerField(default=993)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.mailbox')),
            ],
        ),
    ]
