# Generated by Django 6.0 on 2025-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_mailbox_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
    ]
