# Generated by Django 6.0 on 2025-12-22 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailmessage_processed_at_mailbox_smtp_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together={('user', 'username')},
        ),
    ]
