# Generated by Django 6.0 on 2025-12-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_mailbox_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='ai_draft_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='priority_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_host',
            field=models.CharField(default='smtp.wp.pl', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='emailmessage',
            unique_together={('mailbox', 'uid')},
        ),
    ]
