# Generated by Django 6.0 on 2026-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_emailmessage_ai_draft_reply_emailmessage_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='thread_summary',
            field=models.TextField(blank=True),
        ),
    ]
